from .scrobbling_approve_keyboard import scrobbling_approve_keyboard
from .scrobbling_cancel_keyboard import scrobbling_cancel_keyboard
from .scrobbling_setup_keyboard import scrobbling_setup_keyboard
from .scrobbling_inline_setup_keyboard import scrobbling_inline_setup_keyboard